// TypingMeter - original typing passages written for this site.
// 50 passages: 16 easy, 17 medium, 17 hard.
const passages = {
  easy: [
    `On Saturday morning, Mia woke up early and looked out of the window. The sky was clear, and the street was quiet. She made a cup of tea, packed a small bag, and walked to the park near her house. A few people were already there, jogging along the path or reading on the benches. Mia sat under a big tree and opened her book. After an hour, she felt calm and happy. It was a simple morning, but it was exactly what she needed after a busy week.`,

    `Our neighborhood bakery opens at six every morning. By the time most people wake up, the smell of fresh bread has already filled the street. The baker works quietly in the back, shaping dough and checking the oven. Customers come in for rolls, cakes, and warm loaves. Some of them stay to chat for a minute or two. The shop is small, but it feels like the center of the neighborhood, and everyone seems to know everyone else there.`,

    `A good habit starts small. If you want to read more, begin with ten minutes each day. If you want to exercise, start with a short walk after dinner. Do not try to change everything at once. Small steps are easier to repeat, and repeating them is what makes them stick. After a few weeks, you will notice that the habit feels natural. Then you can add a little more time, and your progress will keep growing without much stress.`,

    `The old bus stopped at the corner of Maple Street, and a group of students got on. They talked about their homework, a school trip, and the weather. The driver smiled and waved to each of them. Outside, rain began to fall softly on the road. Inside, the bus was warm and bright. A girl near the window drew a small star on the foggy glass and watched it slowly disappear as the bus rolled toward the school.`,

    `Cooking at home does not have to be hard. Start with a few simple ingredients, such as rice, eggs, and fresh vegetables. Heat a pan, add a little oil, and cook the vegetables until they are soft. Then add the rice and the eggs, and stir everything together. Add some salt and pepper, and your meal is ready in about fifteen minutes. It is quick, cheap, and much better than most people expect from such a short recipe.`,

    `Every evening, Daniel takes his dog for a walk along the river. The dog, a small brown terrier named Pepper, likes to run ahead and then wait for him at the next bridge. They pass fishermen, cyclists, and families with young children. When the sun goes down, the water turns orange and gold. Daniel usually stops for a moment to watch it. He says that this short walk is the best part of his day, and Pepper clearly agrees.`,

    `Learning a new skill takes time, and that is perfectly normal. At first, everything feels slow and awkward. You make mistakes, and you may want to give up. But with regular practice, your hands and your mind begin to work together. Tasks that once felt hard become easier, and soon you can do them without thinking. The key is to keep going, even on the days when you do not feel like it. Progress is often quiet, but it is real.`,

    `The library in our town is a peaceful place. It has tall windows, wooden tables, and rows of books that stretch all the way to the back wall. On weekends, children gather in the reading corner to listen to stories. Students study at the long tables, and older readers browse the newspapers. The librarian knows almost everyone by name. When you step inside, the noise of the street fades away, and it feels easy to relax and think.`,

    `Last summer, my family drove to the coast for a short vacation. We rented a small house near the beach and spent most of our time outside. In the morning, we walked along the sand and collected shells. In the afternoon, we swam and played games. At night, we sat on the porch and listened to the waves. It was a simple trip with no big plans, yet we still talk about it whenever we want to remember a happy week.`,

    `Good sleep is one of the easiest ways to feel better during the day. Try to go to bed at about the same time each night, and keep your room cool and quiet. Turn off bright screens an hour before bed, and read a book or listen to soft music instead. In the morning, open the curtains and let in the daylight. After a few days, many people notice that they wake up with more energy and think more clearly.`,

    `The market opens early on Sunday. Farmers arrive with trucks full of apples, carrots, tomatoes, and flowers. They set up their tables and arrange everything in neat rows. Soon the first customers appear, carrying cloth bags and cups of coffee. Children point at the bright fruit, and musicians play near the entrance. By noon, the best things are almost gone. If you want fresh bread or ripe peaches, you need to arrive before the crowd.`,

    `When Sara started her first job, she was nervous about everything. She worried about being late, forgetting names, and asking too many questions. But her coworkers were kind, and her manager told her that questions are a sign of interest, not weakness. Within a month, she knew her way around the office and had made two good friends. Looking back, she laughed at how afraid she had been. Her advice to new people is simple: be patient, be curious, and be yourself.`,

    `A garden does not need much space to be useful. A few pots on a balcony can hold herbs, flowers, or even small tomatoes. Place them where they get plenty of sun, and water them every morning. Check the leaves from time to time, and remove any that look dry or damaged. In a few weeks, you will see new growth. There is something very satisfying about picking a fresh leaf from a plant you have grown yourself.`,

    `The train left the station exactly on time. Passengers found their seats, put their bags on the shelves, and settled in for the ride. Outside, the city slowly turned into fields and small villages. A man across the aisle was reading a newspaper, and a young woman was typing on her laptop. The conductor walked through the car and checked each ticket with a polite nod. It was an ordinary trip, but the view from the window made it feel special.`,

    `Friendship often grows from small moments. A shared joke, a quick message, or a short walk can build trust over time. You do not need to see your friends every day to stay close. What matters is that you listen when they speak and show up when they need help. Even a short call can mean a lot on a hard day. The best friendships are not loud or dramatic. They are steady, kind, and easy to return to.`,

    `On rainy days, our family likes to stay inside and play board games. We pull out the old box from the shelf, clear the table, and make a big bowl of popcorn. Everyone chooses a favorite piece and tries to win. Sometimes the games last for hours, and nobody notices the time. Even when the rain stops, we often keep playing for one more round. It is a small tradition, but it brings us together every time.`
  ],

  medium: [
    `Remote work has changed how many people think about their daily routines. Without a long commute, workers often gain an extra hour each morning, which they can spend on exercise, breakfast, or quiet planning. However, the lack of clear boundaries can be a problem. When the kitchen table is also the office, it becomes hard to stop answering messages at night. Many people now set a fixed schedule, create a dedicated workspace, and take short walks between tasks to protect their focus and energy.`,

    `Public libraries are evolving far beyond shelves of printed books. Today, many of them offer free internet access, language classes, job-search workshops, and quiet rooms for study. Some even lend tools, musical instruments, and seeds for home gardens. This shift reflects a simple idea: a library is a shared resource that helps people learn, no matter their age or income. As technology changes, these institutions continue to adapt, and they remain one of the most useful public services in a community.`,

    `Coffee has a long and surprising history. According to a popular legend, a goat herder noticed that his animals became lively after eating the red berries of a certain bush. Whether or not the story is true, coffee spread from East Africa across the Arabian Peninsula and eventually into Europe. Cafes became places where merchants, writers, and thinkers exchanged ideas. Even today, a cup of coffee is often the center of a conversation, a meeting, or a quiet moment before the day begins.`,

    `Urban gardens are becoming more common in crowded cities. Rooftops, empty lots, and balconies are being turned into small farms that produce vegetables, herbs, and flowers. These spaces help reduce heat, support local insects, and give residents a way to connect with nature. They also teach children where food comes from. Although a single garden cannot feed an entire city, many of them together can improve air quality, strengthen communities, and make busy neighborhoods feel greener and calmer.`,

    `Learning to type without looking at the keyboard is a skill that pays off for years. At first, progress may feel slow because your fingers are still searching for the correct keys. The best approach is to focus on accuracy and let speed come naturally. Keep your wrists relaxed, sit with a straight back, and use the same finger for the same key every time. After a few weeks of regular practice, many learners are surprised at how automatic the movements become.`,

    `Weather forecasts are based on data collected from satellites, weather stations, balloons, and ocean buoys. Computers use this information to run models that predict how the atmosphere will change over the next several days. Short-term forecasts are usually quite accurate, while longer ones become less certain because small changes can grow into large differences. This is why meteorologists talk about probabilities, such as a sixty percent chance of rain, rather than promising exactly what will happen.`,

    `The bicycle is one of the most efficient machines ever invented. It converts human effort into forward motion with very little waste, and it needs no fuel other than food. In many cities, bike lanes have made commuting faster, cheaper, and healthier. Riding also reduces traffic and noise. For short trips, a bicycle can easily beat a car, especially during rush hour. With a helmet, a good light, and a little caution, cycling can become a reliable part of everyday life.`,

    `Good teachers do more than explain facts. They notice when a student is confused, adjust their examples, and create an environment where it feels safe to ask questions. A single encouraging comment can change how a young person sees a subject. Research often shows that students remember not only what they learned but also how they were treated. In that sense, a classroom is not just a place for information. It is a place where confidence, curiosity, and respect can grow together.`,

    `Every language is a record of how its speakers live and think. Some languages have many words for snow, others for family relationships, and others for different kinds of politeness. When a language disappears, a unique way of describing the world disappears with it. Linguists, teachers, and local communities are working together to record and teach endangered languages. Their efforts include dictionaries, storytelling projects, and online lessons, so that younger generations can speak the language of their grandparents.`,

    `Sleep is not just a break from the day; it is an active process that helps the body and brain recover. During deep sleep, the body repairs tissue and strengthens the immune system. During dream sleep, the brain sorts memories and connects new information with old knowledge. People who sleep poorly often struggle with attention, mood, and decision-making. For most adults, seven to nine hours a night is a healthy target, though individual needs can vary slightly.`,

    `A balanced budget does not need to be complicated. Start by writing down your monthly income, then list your fixed costs, such as rent, transport, and bills. Next, set aside a small amount for savings before you spend anything on extras. Track your spending for a month to see where the money actually goes. Many people are surprised by how much they spend on small, regular purchases. Once you see the pattern, it becomes much easier to make changes that you can maintain.`,

    `Sound travels as waves of pressure through the air. When you speak, your vocal cords vibrate and push the air around them, and those vibrations reach the ears of the listener. The pitch of a sound depends on how fast the vibrations occur, while its volume depends on how strong they are. In space, there is no air, so sound cannot travel. That is why astronauts use radios to talk, even when they are standing only a few feet apart.`,

    `The first step in solving a difficult problem is to describe it clearly. Many people jump straight to solutions, only to find that they were answering the wrong question. Write down what you know, what you do not know, and what a good result would look like. Then break the problem into smaller parts and work on them one at a time. This method may feel slow at first, but it usually saves time and prevents unnecessary mistakes later on.`,

    `Museums do more than store old objects. Curators study each item carefully, record where it came from, and decide how it should be displayed and protected. A well-designed exhibit tells a story that visitors can understand without reading long explanations. Many museums now offer digital tours, so that people far away can explore their collections online. Still, standing in front of a real painting, tool, or fossil often creates a feeling that a screen cannot fully reproduce.`,

    `Volunteering is a way of giving time instead of money. People volunteer in food banks, animal shelters, hospitals, schools, and community gardens. The benefits go in both directions: organizations receive much-needed help, and volunteers often gain new skills, friendships, and a stronger sense of purpose. You do not need special training to start. Many groups only ask for reliability and a positive attitude. Even a few hours each month can make a real difference in a neighborhood.`,

    `Mountains affect weather in powerful ways. When moist air reaches a mountain range, it is forced upward, where it cools and forms clouds. This often leads to heavy rain or snow on the windward side. On the other side, the air descends and becomes dry, creating what is known as a rain shadow. As a result, two places only a short distance apart can have very different climates, with green forests on one side and open, dry land on the other.`,

    `Photography has changed greatly since the first cameras appeared. Early photographers needed long exposure times, heavy equipment, and special chemicals. Today, almost everyone carries a camera in their pocket and can share an image within seconds. Yet the basics remain the same: light, framing, and timing. A thoughtful photograph is not about expensive gear. It is about noticing something worth showing and arranging the scene so that other people can notice it too.`
  ],

  hard: [
    `In 2024, a small research team measured air quality at 42 locations across the city, collecting samples every 15 minutes between 6:00 a.m. and 10:00 p.m. Their results, published in a 38-page report, showed that nitrogen dioxide levels were 27% higher near major intersections than in residential areas. "The difference is significant," the lead author wrote, "but it can be reduced with better traffic planning." The team recommended three changes: synchronized signals, more bus lanes, and tree-lined barriers.`,

    `A well-structured database depends on careful design. Each table should represent one type of entity, such as customers, orders, or products, and each row should be identified by a unique key. When tables are connected through foreign keys, queries like SELECT name, total FROM orders WHERE total > 500; can return accurate results quickly. Poor design, on the other hand, leads to duplicate records, slow searches, and confusing errors. Normalization, indexing, and regular backups are therefore essential practices.`,

    `The expedition left the base camp at 5:30 a.m., carrying 18 kilograms of equipment per person. By noon, the temperature had dropped to -12 degrees Celsius, and a steady wind made every step harder. Despite the conditions, the group reached the ridge at 3:45 p.m. and set up two tents beside a frozen stream. That night, the leader reviewed the route, checked the radio, and reminded everyone: "Rest well; tomorrow's climb is the most difficult part of the journey."`,

    `Photosynthesis is the process by which plants, algae, and some bacteria convert light energy into chemical energy. Inside the chloroplasts, chlorophyll absorbs sunlight and uses it to transform carbon dioxide and water into glucose and oxygen. The simplified equation, 6CO2 + 6H2O -> C6H12O6 + 6O2, hides a series of complex reactions, including the light-dependent stage and the Calvin cycle. Without this process, most ecosystems on Earth would not be able to survive.`,

    `Cybersecurity is not only a technical issue; it is also a human one. Strong passwords, two-factor authentication, and regular software updates protect accounts, but careless clicks can still expose sensitive data. Attackers often send convincing messages that pretend to come from banks, employers, or delivery services. If an email asks you to verify your account immediately, pause and check the sender's address. When in doubt, visit the official website directly rather than following an unexpected link.`,

    `Inflation describes a general rise in prices over time, usually measured by an index that tracks the cost of everyday goods and services. When inflation is moderate, say around 2% per year, it can accompany a healthy, growing economy. When it accelerates, however, savings lose value, wages struggle to keep pace, and planning becomes difficult. Central banks respond by adjusting interest rates, balancing two risks: slowing the economy too much, or allowing prices to rise out of control.`,

    `The architect's proposal included a 12-story building with a glass facade, a rooftop garden, and an underground parking area for 140 vehicles. According to the budget, the project would cost approximately $48.6 million and take about 26 months to complete. Several residents objected, arguing that the structure would block sunlight and increase traffic. In response, the design team revised the plan, lowering the height by two floors and adding a small public square at the entrance.`,

    `Quantum computers use qubits, which can exist in a combination of states rather than simply 0 or 1. When qubits become entangled, the state of one is linked with the state of another, even if they are physically separated. Researchers hope to use these properties to solve certain problems, such as modeling molecules, far faster than classical machines. However, qubits are fragile; heat, vibration, and electromagnetic noise can easily disturb them, so building reliable systems remains a major challenge.`,

    `Dear Ms. Alvarez, thank you for your message of March 14th. I have reviewed the contract carefully, and I would like to propose three adjustments: first, that the delivery date be moved from June 30 to July 15; second, that payment be made in two installments rather than one; and third, that either party may cancel with 30 days' written notice. If these terms are acceptable, I will send the revised document by Friday. Sincerely, J. Whitfield.`,

    `The marathon route covered 42.195 kilometers, beginning at the old harbor and finishing in the central square. By kilometer 30, the leading group had narrowed to four runners, each maintaining a pace of roughly 3 minutes and 5 seconds per kilometer. Spectators lined the streets, ringing bells, waving flags, and offering cups of water. Although the winner crossed the line in 2:09:47, many believe that the most inspiring finishers were those who arrived hours later, exhausted but smiling.`,

    `Effective writing is rarely accidental. Before drafting, a good writer decides who the readers are, what they already know, and what they need to understand by the end. Sentences should be clear, concrete, and varied in length; unnecessary words should be removed. During revision, read the text aloud, because awkward phrasing is easier to hear than to see. Finally, check details such as spelling, punctuation, names, dates, and numbers; small errors can quietly damage trust.`,

    `Glaciers are enormous, slow-moving rivers of ice that form where snowfall exceeds melting over many years. As new snow compresses older layers, it gradually becomes dense, blue-tinted ice. Over the past several decades, many glaciers have retreated significantly, exposing bare rock and feeding rivers with extra meltwater. Scientists monitor these changes using satellite imagery, drones, and stakes drilled into the ice, because glaciers store fresh water that millions of people depend on.`,

    `To install the software, first download the package from the official website and verify its checksum. Next, open a terminal and run: sudo apt update && sudo apt install ./tool-2.4.1.deb. If the installation fails, check whether the required libraries (for example, libssl and zlib) are present. After the setup completes, launch the program with tool --init, then edit the configuration file located in ~/.config/tool/settings.json to match your preferences.`,

    `The city council voted 7-2 to approve the new transit plan, which includes 15 kilometers of dedicated bus lanes, 30 additional stops, and a fare system that allows free transfers within 90 minutes. Supporters argued that the plan would shorten commutes and reduce emissions. Critics, however, warned about construction delays and rising costs. The first phase is expected to begin in the spring, with a progress review scheduled for December and a public meeting every quarter.`,

    `Antibiotics are medicines designed to fight bacterial infections, but they are ineffective against viruses such as the common cold or influenza. Using them unnecessarily can contribute to antibiotic resistance, a growing problem in which bacteria evolve to survive treatment. To help prevent this, patients should take prescribed doses exactly as directed, complete the full course unless a doctor says otherwise, and never share leftover pills. Doctors, in turn, prescribe them only when they are truly needed.`,

    `Archaeologists working at the site uncovered pottery fragments, bronze tools, and the foundations of several rectangular buildings, which they dated to roughly 1200 BCE. Careful analysis of the soil revealed traces of wheat, barley, and olive oil, suggesting that the settlement relied on farming and trade. Maps, photographs, and detailed notes were recorded for every layer; as one team member explained, "Once a trench is excavated, the context can never be recreated, so documentation is everything."`,

    `Choosing a laptop depends on how you plan to use it. For writing and browsing, 8 GB of memory and a 256 GB solid-state drive are usually enough. Video editing, programming with virtual machines, or modern gaming may require 16 GB or more, a faster processor, and a dedicated graphics card. Battery life, screen quality, keyboard comfort, and weight also matter, because you will interact with them every day. Compare reviews, but trust your own hands-on impressions, too.`
  ]
};