(() => {
  'use strict';
  const KEY = 'typingmeterWordScrambleHistory';
  const MAX = 100;
  const BANK = {
    easy: ['apple', 'bread', 'chair', 'cloud', 'dance', 'dream', 'earth', 'flame', 'flower', 'green', 'happy', 'house', 'light', 'music', 'paper', 'plant', 'quick', 'river', 'school', 'smile', 'snake', 'sound', 'star', 'stone', 'table', 'tiger', 'water', 'world', 'yellow', 'zebra', 'friend', 'garden', 'summer', 'winter', 'window', 'orange', 'purple', 'rabbit', 'rocket', 'sunny'],
    medium: ['balance', 'browser', 'capture', 'challenge', 'classic', 'comfort', 'connect', 'correct', 'diamond', 'evening', 'freedom', 'journey', 'library', 'machine', 'morning', 'network', 'picture', 'practice', 'problem', 'project', 'quality', 'rhythm', 'science', 'service', 'station', 'success', 'teacher', 'through', 'traffic', 'typical', 'uniform', 'victory', 'weather', 'welcome', 'without', 'ability', 'country', 'improve', 'message'],
    hard: ['algorithm', 'attention', 'beautiful', 'coordinate', 'curiosity', 'determination', 'experience', 'generation', 'imagination', 'independent', 'information', 'knowledge', 'motivation', 'opportunity', 'performance', 'responsibility', 'technology', 'understanding', 'vocabulary', 'architecture', 'concentration', 'environment', 'extraordinary', 'flexibility', 'professional', 'recognition', 'significant', 'transformation', 'communication', 'consistency']
  };
  const $ = id => document.getElementById(id);
  const els = { time: $('timeValue'), score: $('scoreValue'), combo: $('comboValue'), best: $('bestValue'), setup: $('setupPanel'), game: $('gamePanel'), result: $('resultPanel'), start: $('startBtn'), word: $('wordArea'), input: $('answerInput'), form: $('answerForm'), feedback: $('feedbackText'), accuracy: $('accuracyValue'), wpm: $('wpmValue'), words: $('wordsValue'), difficulty: $('difficultyBadge'), progress: $('progressText'), resultTitle: $('resultTitle'), resultScore: $('resultScore'), resultWords: $('resultWords'), resultAccuracy: $('resultAccuracy'), resultWpm: $('resultWpm'), resultCombo: $('resultCombo'), resultMessage: $('resultMessage'), again: $('againBtn'), settings: $('settingsBtn'), quit: $('quitBtn'), history: $('historyList'), clear: $('clearHistoryBtn') };
  let difficulty = 'easy', duration = 60, timeLeft = 60, timer = null, startedAt = 0, current = '', score = 0, combo = 0, bestCombo = 0, correct = 0, attempts = 0, words = 0, roundFinished = false, used = new Set();
  const getBest = () => readHistory().reduce((m, x) => Math.max(m, Number(x.score) || 0), 0);
  function readHistory() { try { const raw = JSON.parse(localStorage.getItem(KEY) || '[]'); return Array.isArray(raw) ? raw.filter(x => x && typeof x === 'object').slice(0, MAX) : [] } catch { return [] } }
  function saveHistory(item) { const list = [item, ...readHistory()].slice(0, MAX); try { localStorage.setItem(KEY, JSON.stringify(list)) } catch { } renderHistory() }
  function renderHistory() { const list = readHistory(); els.history.innerHTML = list.length ? list.map(x => `<div class="history-item"><div class="date">${escapeHtml(new Date(x.date).toLocaleString())}<div class="muted">${escapeHtml(x.difficulty)} · ${x.duration}s</div></div><div><span class="muted">Score</span><strong>${Number(x.score) || 0}</strong></div><div><span class="muted">WPM</span><strong>${Number(x.wpm) || 0}</strong></div><div><span class="muted">Accuracy</span><strong>${Number(x.accuracy) || 0}%</strong></div><div><span class="muted">Words</span><strong>${Number(x.words) || 0}</strong></div></div>`).join('') : `<p style="color:#777;text-align:center;margin:8px 0">Your completed games will appear here.</p>`; els.best.textContent = getBest() }
  function escapeHtml(v) { return String(v).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])) }
  function scramble(word) { if (word.length < 2) return word; let a = word.split(''), original = word, tries = 0; do { for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1));[a[i], a[j]] = [a[j], a[i]] } tries++ } while (a.join('') === original && tries < 8); return a.join('') }
  function nextWord() { const bank = BANK[difficulty]; let word = ''; for (let i = 0; i < 20; i++) { word = bank[Math.floor(Math.random() * bank.length)]; if (!used.has(word) || used.size >= bank.length - 2) break } used.add(word); if (used.size > bank.length - 2) used.clear(); current = word; els.word.textContent = scramble(word); els.progress.textContent = `Word ${words + 1}`; els.input.value = ''; els.input.focus() }
  function accuracy() { return attempts ? Math.round(correct / attempts * 100) : 100 }
  function wpm() { if (!startedAt) return 0; const mins = Math.max((Date.now() - startedAt) / 60000, 1 / 60000); return Math.round((correct / mins)) }
  function update() { els.time.textContent = `${Math.max(0, timeLeft)}s`; els.score.textContent = score; els.combo.textContent = combo; els.accuracy.textContent = `${accuracy()}%`; els.wpm.textContent = wpm(); els.words.textContent = words }
  function start() { clearInterval(timer); timeLeft = duration; score = 0; combo = 0; bestCombo = 0; correct = 0; attempts = 0; words = 0; used.clear(); roundFinished = false; startedAt = Date.now(); els.setup.classList.add('hidden'); els.result.classList.add('hidden'); els.game.classList.remove('hidden'); els.difficulty.textContent = difficulty.toUpperCase(); els.feedback.textContent = ''; els.feedback.className = 'feedback'; update(); nextWord(); timer = setInterval(() => { timeLeft--; update(); if (timeLeft <= 0) finish(false) }, 1000) }
  function finish(quit) { if (roundFinished) return; roundFinished = true; clearInterval(timer); timer = null; const acc = accuracy(), wp = wpm(); els.game.classList.add('hidden'); els.result.classList.remove('hidden'); els.resultTitle.textContent = quit ? 'Game ended' : 'Time is up!'; els.resultScore.textContent = score; els.resultWords.textContent = words; els.resultAccuracy.textContent = `${acc}%`; els.resultWpm.textContent = wp; els.resultCombo.textContent = bestCombo; els.resultMessage.textContent = quit ? 'Your round was not saved.' : 'Nice run! Try another round to beat your score.'; if (!quit) saveHistory({ date: new Date().toISOString(), difficulty, duration, score, wpm: wp, accuracy: acc, words, bestCombo }) }
  els.start.addEventListener('click', start); document.querySelectorAll('[data-difficulty]').forEach(b => b.addEventListener('click', () => { difficulty = b.dataset.difficulty; document.querySelectorAll('[data-difficulty]').forEach(x => x.classList.toggle('active', x === b)) })); document.querySelectorAll('[data-time]').forEach(b => b.addEventListener('click', () => { duration = Number(b.dataset.time); document.querySelectorAll('[data-time]').forEach(x => x.classList.toggle('active', x === b)); els.time.textContent = `${duration}s` })); els.form.addEventListener('submit', e => { e.preventDefault(); if (roundFinished) return; const answer = els.input.value.trim().toLowerCase(); if (!answer) return; attempts++; if (answer === current) { correct++; words++; combo++; bestCombo = Math.max(bestCombo, combo); score += 10 + Math.min(combo - 1, 10) * 2; els.feedback.textContent = '✓ Correct!'; els.feedback.className = 'feedback correct'; nextWord() } else { combo = 0; els.feedback.textContent = 'Not quite — try again.'; els.feedback.className = 'feedback wrong'; els.input.select() } update() }); els.quit.addEventListener('click', () => finish(true)); els.again.addEventListener('click', start); els.settings.addEventListener('click', () => { els.result.classList.add('hidden'); els.setup.classList.remove('hidden') }); els.clear.addEventListener('click', () => { if (!readHistory().length) return; if (confirm('Clear Word Scramble history?')) { localStorage.removeItem(KEY); renderHistory() } }); els.input.addEventListener('paste', e => e.preventDefault()); els.input.addEventListener('drop', e => e.preventDefault()); window.addEventListener('storage', renderHistory); renderHistory(); update();
})();
